version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${DATABASE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_http_websockets:

    build:
        context: .
        dockerfile: Dockerfile
    container_name: ${FASTAPI_HTTP_WEBSOCKETS_CONTAINER_NAME}
    env_file:
        - .env
    environment:
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
    ports:
        - "8000:8000"
        - "8001:8001"
    depends_on:
        - postgres

volumes:
  postgres_data:
