FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY Prerequisites/SMTP /app

EXPOSE 10000

CMD ["python", "-u", "run_smtp_server.py"]
